export const GET_ALLPRODUCTS_SUCCESS="GET_ALLPRODUCTS_SUCCESS"
export const GET_ALLPRODUCTS_FAIL="GET_ALLPRODUCTS_FAIL"
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL="UPDATE_PRODUCT_FAIL"
export const GET_ONE_PRODUCT_SUCCESS="GET_ONE_PRODUCT_SUCCESS"
export const GET_ONE_PRODUCT_FAIL="GET_ONE_PRODUCT_FAIL"
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY ='UPDATE_CART_ITEM_QUANTITY';


