export const GET_ALLPRODUCTS_SUCCESS="GET_ALLPRODUCTS_SUCCESS"
export const GET_ALLPRODUCTS_FAIL="GET_ALLPRODUCTS_FAIL"
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL"
